@RestController
@RefreshScope
public class ServiceAController {
 @Value("${greeting}")
 private String greeting;

 @Value("${message}")
 private String message;

 @RequestMapping("/")
 public String getName() {
 return message+" , "+greeting;
 }
} 
